approvedGitRepositories:
  - github.com/visitscotland/*

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@visitscotland/component-library"

yarnPath: .yarn/releases/yarn-4.16.0.cjs
