name: PR to develop

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
    audit:
        uses: ./.github/workflows/yarn-audit.yml
        secrets: inherit
        
    complete:
        needs: audit
        runs-on: ubuntu-latest
        steps:
            - name: Finish task
              run: echo 'Task finished'

