name: PR to develop

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        branches: master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: install
              run: yarn install

    audit:
        uses: ./.github/workflows/yarn-audit.yml
        secrets: inherit            

