name: Yarn-Audit
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Yarn Audit
      uses: pragatheeswarans/yarn-audit-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        assignee: 'jameshaddrillvs'
        label: 'audit issues'
        title: 'yarn audit dependency issues'
