name: Yarn-Audit
on:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run auditjs
        run: |
          yarn install
          npx auditjs@beta ossi
     
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: success message
        run: echo "Mission accomplished!"
