name: Yarn audit
on:
  workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run auditjs
        run: |
          yarn install
          npx auditjs@beta ossi

