name: Yarn-Audit
on:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run auditjs
      run: |
        px auditjs@beta ossi
